### ISSUE TITLE
it looks like powerful, but I don't know how to use

### ISSUE THREAD

**Issue by jiqimaogou** [pardom/Ollie#12]

**Comment by PerfectCarl** [comment]
@jiqimaogou I'm trying to set ollie with Eclipse and the files are not generated.

So far I have all the compiler files in a folder in my project and I registered the ollie compiler in the annotation processor but the files are not generated.

![Imgur](http://i.imgur.com/ve0BSMe.png)

![Imgur](http://i.imgur.com/7ZCyZV3.png)

Is this a dependency issue?

Here's my file: 

``` java
package rainstudios.white.data;

import ollie.Model;
import ollie.annotation.Column;
import ollie.annotation.Table;

@Table("notes")
class Note extends Model {
    @Column("title")
    public String title;
    @Column("body")
    public String body;
}
```

**Comment by PerfectCarl** [comment]
I found the reason. 

For some reason, the folder `.apt-generated` was wiped each time a build took place. 
I don't know why. Maybe it's because I use kotlin/xtend in parallel, but renaming the folder to `.apt-get` fixed it.

Weird.
