### ISSUE TITLE
What to do when the model's id has to be String

### ISSUE THREAD

**Issue by lapastillaroja** [pardom/Ollie#36]
I have multiple DTOs to parse data from my application's backend API. In this API all objects `id`s are `String`. However Ollie's `Model` class `id` property is `Long`, so it conflicts with my API.

In ActiveAndroid Model's `id` was private and there was an `getId` method that suited very well in this situation. The application is already working with ActviveAndroid and the API can't be changed.

Have you any clues?

Btw, I'm using Retrofit and Gson on the API side.

**Comment by pardom** [comment]
Have a look at this answer. https://github.com/pardom/Ollie/issues/38#issuecomment-70501843
