### ISSUE TITLE
db field has null-value

### ISSUE THREAD

**Issue by Rainer-Lang** [pardom/Ollie#39]
I have an integer column with null-values inside. I store dates in this col.
If I load the ollie-object I always get dates with 0 -> 01.01.1970
How can I get the null value (stored in the database) back?

If I load the value from db with fetchValue(String.class) I get the null value...

**Comment by pardom** [comment]
I don't quite understand your scenario. Can you give some example code of what you're doing?

**Comment by Rainer-Lang** [comment]
I have a column to store a birthday of a person - in database type "long".
In my Ollie-Object I use :
@Column(BIRTHDAY)
public Calendar m_dtBirthday;

So if I load the person the birthday is also loaded.

Now, if the user doesn't specify the birthday - m_dtBirthday is NULL and this is also saved in database. That's fine!
After loading the person from database m_dtBirthday==0 - so the birthday will be shown as 01.01.1970 instead of "undefined"/NULL-value.

**Comment by markini** [comment]
Default value for `Long` and `Integer` is 0 in Ollie. 
When you retrieve a Long which was set to null from the database it will give you 0.

Therefore you can but shouldn't compare with 0. Why not using a `Date` or an [ISO 8601 String](https://en.wikipedia.org/wiki/ISO_8601)?

**Comment by Rainer-Lang** [comment]
Calendar goes to integer value in database. But this field could also be null.
And if you read the Calendar back you get not null but 0.
For me this is a bug. Other orm libs handle this correctly and gives the value which is in the database - and this is null.

**Comment by pardom-zz** [comment]
Ah, Okay. There was a similar bug with BooleanAdapter. I'll take a PR or fix it soon.

**Comment by markini** [comment]
~~I wouldn't consider this a bug. Non wrapped integer values also have 0 as default value. It's more a design decision.~~

~~The issue with BooleanAdapter was something else: it threw a `NullpointerException` when saving null values. (when trying to read null values from the database)~~

~~Edit: I know, we are talking about Calendar. But this is also rather a design decision if this should have a default value.~~

Edit 2: scratch that. Yes Calendar should be null I agree.

**Comment by Rainer-Lang** [comment]
@markini Thanks for edit2. :-D

**Comment by pardom-zz** [comment]
Ah, sorry I only skimmed the comments. This is actually a problem with using `Cursor.getLong()` as it returns a primitive `long`. I'll have a look at correcting this with `Cursor.isNull()`.

**Comment by Rainer-Lang** [comment]
@pardom Thanks Michael.
