### ISSUE TITLE
Compilation fails with an NullPointerException

### ISSUE THREAD

**Issue by Saketme** [pardom/Ollie#41]
Hello. Before anything else, thanks for creating Ollie. Now, I cannot understand why, but I'm unable to build my project with this library. The only error I'm seeing is:

    Error:Execution failed for task ':SMSX:compileDebugJava'.
    > java.lang.NullPointerException

That's it. Nothing else. Model class: https://gist.github.com/anonymous/3c3cb0465b8ecdd2ee57

I'm initializing Ollie inside my Application class. Any idea how to fix this? Thank you.

Update: So replacing the primitives in my model class with their Wrapper classes fixed the issue. Am I doing this right?

**Comment by lauw** [comment]
Yes you can only use the wrapper classes of the basic types. I agree you have to puzzle a bit to solve the NPE's since there's nothing to go by.

Lists aren't supported either.
If you want enum support you can use a TypeAdapter

example:
```java
	public static class TestTypeAdapter extends TypeAdapter<TestEnum, Integer> {
		@Override
		public Integer serialize(TestEnum value) {
			return value.ordinal();
		}

		@Override
		public TestEnum deserialize(Integer value) {
			return TestEnum.valueOf(value);
		}
	}
```

**Comment by Saketme** [comment]
Thank you. I'm so far loving this library even though there's a lot of undocumented stuff. I also found that non-default constructors are not supported either. 

It'd be excellent if the Readme file was updated with things that are unsupported. Sorry if this is a noob question, but can I send a pull request with contributions for the Readme file?

**Comment by pardom** [comment]
@Saketme looking at your gist, the problem is that you're using primitive types. Primitive types are not supported — a design choice because they break the analogy of a nullable column. If you with the column to be not null, you can use the `@NotNull` annotation.

Instead of updating the Readme file, I'll start working on the wiki. This way people can make contributions without effecting the commits.

**Comment by pardom** [comment]
@Saketme Oh, and about constructors. You can have all the constructors you like so long as you also have the constructor that Ollie expects, which is the empty constructor.

https://github.com/pardom/Ollie/blob/master/core/src/main/java/ollie/Ollie.java#L173

**Comment by Saketme** [comment]
A Wiki would be great. Thank you :)
