### ISSUE TITLE
Ollie and ContentProvider

### ISSUE THREAD

**Issue by Rainer-Lang** [pardom/Ollie#45]
Is someone using this?

**Comment by ciprig** [comment]
The content provider doesn't seems to be generated, or I'm doing something wrong?

I use com.neenbedankt.android-apt, btw this should be added in the readme on how to use lib.

**Comment by saket** [comment]
I looked up the test classes and read @pardom's other ORM library (ActiveAndroid)'s Wiki and found that using Ollie's ContentProvider is fairly easy. Here's how:
1. Extend `OllieProvider`:
   ```
   public static class MyContentProvider extends OllieProvider{
       @Override
       protected String getDatabaseName() {
           return DATABASE_NAME;
       }
   
       @Override
       protected int getDatabaseVersion() {
           return DATABASE_VERSION;
       }
   }
   ```
   
2. Register the provider in your Manifest:
   
   ```
    <provider
       android:name=".database.MyContentProvider "
       android:authorities="me.saket.define"
       android:enabled="true"
       android:exported="false" />
    ```
3. Use it!
    ```
    @Override
    public Loader<Cursor> onCreateLoader(int id, Bundle args) {
        final Uri uri = MyContentProvider.createUri(YourOllieModel.class);
        return new CursorLoader(this, uri, null, null, null, null);
    }
    ```

That's it. I wish @pardom had created a wiki already so that I could start contributing to it.

**Comment by sal0max** [comment]
Is it possible to create a `Uri` or maybe a custom `ContentProvider` for joined tables with Ollie?

Like I'd want not only all the data of my table `employees`, but additionally all data of table `salaries` from [this database structure](https://dev.mysql.com/doc/employee/en/sakila-structure.html).
