### ISSUE TITLE
ClassNotFoundException: ollie.AdapterHolderImpl

### ISSUE THREAD

**Issue by Saketme** [pardom/Ollie#51]
Hi, so I have just integrated Ollie in my newest app and it is giving me strange errors. It compiles without any errors, but crashes right on startup.

Here's the stacktrace: https://gist.github.com/anonymous/a8d3fcb2fb4cd92a2dc4

I believe I've added it using Gradle the right away:

    compile 'com.michaelpardo:ollie:0.3.1'
    provided 'com.michaelpardo:ollie-compiler:0.3.1'

Here's the model:

    @Table(SavedDefinitions.TABLE_NAME)
    public class SavedDefinitionEntry extends Model {

        // Data
        @Column(SavedDefinitions.KEY_WORD)              public String mWord;
        @Column(SavedDefinitions.KEY_PHONETIC_TEXT)     public String mPhoneticText;

        public SavedDefinitionEntry(String mWord, String mPhoneticText) {
            this.mWord = mWord;
            this.mPhoneticText = mPhoneticText;
        }

    }

I am having a hard time solving this error. Any ideas? :(

**Comment by pardom** [comment]
What do the generated sources look like?

**Comment by Saketme** [comment]
I'm sorry, but where do I find them?

**Comment by pardom** [comment]
Depends on your build tool.

**Comment by Saketme** [comment]
SDK build tool do you mean? My project is using v21.1.1

Also, I have seen generated java files of other libraries (like ButterKnife) inside `\build\generated\source\apt` but I cannot find anything for Ollie there

**Comment by Saketme** [comment]
Update: I cannot find any generated files. I can see them for my other project inside `\build\intermediates\classes\debug\ollie`, but none for this one.

**Comment by pardom** [comment]
Try using APT.

**Comment by Saketme** [comment]
Can you please elaborate a bit? I don't what APT is. Does it have to do anything with this library: 

https://bitbucket.org/hvisser/android-apt

**Comment by pardom** [comment]
Yeah, I thought you were processing with apt.

**Comment by Saketme** [comment]
This is the first time I have heard about APT. I now feel like a noob. Adding android-apt to my project. Will let you know how it goes from there.

**Comment by pardom** [comment]
If you're not already doing that then there's no use. Ollie will work with javac. I assume there are not compiler errors?

**Comment by Saketme** [comment]
No, AndroidStudio isn't showing any compile errors and that's what has me puzzled.

**Comment by Saketme** [comment]
Interestingly, my other project (where Ollie is working perfectly) does not include apt in its build.gradle file. I tried removing it from this project as well, but I'm then having Gradle errors.

**Comment by ciprig** [comment]
I have same error but I need apt for dagger, and it used to work.

**Comment by SeaSheep** [comment]
I search AdapterHolderImpl.java file in source.
But I did't find it.
Where the file?
