### ISSUE TITLE
Delete columns if parent is deleted

### ISSUE THREAD

**Issue by markini** [pardom/Ollie#55]
I have a model like this:

``` java
@Table("note")
public class Note extends Model {
        public static final String TITLE = "title";
        public static final String TAG = "tag";

        @Column(TITLE)
        public String title;
        @Colume(TAG)
        public Tag tag;
}
```

Tag is also a model. Is there a way that, when I say `note.delete()` that the corresponding tag also gets deleted (like with e.g. `@ForeignKey(onDelete = CASCADE)`).

**Comment by NeoLSN** [comment]
https://github.com/pardom/Ollie/blob/master/core/src/test/java/ollie/test/model/NoteTag.java

**Comment by markini** [comment]
Hmm yeah, I know, that when I make the Tag class like this:

``` java
@Table("tag")
public class Tag extends Model {
        public static final String TITLE = "title";
        public static final String NOTE = "note";

        @Column(TITLE)
        public String title;

        @Colume(NOTE)
        @ForeignKey(onDelete = CASCADE)
        public Note note;
}
```

It would get deleted, when I delete a Note. Then I couldn't set a tag member like this in the note: 

``` java
        @Colume(TAG)
        public Tag tag;
```

(circular dependency). 
But if there are no possibilities to solve this issue without the child having a foreignKey of the parent, I will implement it like this I guess.
