### ISSUE TITLE
Is somebody using Ollie and RxJava?

### ISSUE THREAD

**Issue by Rainer-Lang** [pardom/Ollie#58]
Just want to know. Maybe I have some questions in future. :-)

**Comment by pardom-zz** [comment]
The tests are using them. :wink:

**Comment by NeoLSN** [comment]
Does this library rely on RxJava or just using them in test cases?

**Comment by pardom-zz** [comment]
Ollie uses RxJava only to create query observables. You are not required to use RxJava.
