### ISSUE TITLE
Multiple Conditions?

### ISSUE THREAD

**Issue by StephenBlackWasAlreadyTaken** [pardom/Ollie#75]
I feel like I must be doing something wrong, but is there no way to chain multiple conditions in a single query 

``` java
Select.from(SomeTable.class)
  .where("a > ?", something)
  .where("b > ?", something_else)
  .fetch()`
```

**Comment by pardom-zz** [comment]
Correct, in the spirit of not straying from SQL syntax, each clause can only be called once unless otherwise specified: https://www.sqlite.org/syntax/select-stmt.html Expressions should be combined with the appropriate `AND`, `OR`, `IN`, etc.

Your example should be written like this:

``` java
Select.from(SomeTable.class)
  .where("a > ? AND b > ?", something, something_else)
  .fetch()
```

**Comment by StephenBlackWasAlreadyTaken** [comment]
Thanks a ton, I knew I was missing something silly! Awesome library!!
